# Generated by Django 4.0.4 on 2022-05-23 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestione', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='id',
            field=models.IntegerField(default=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prenotazione', models.DateField(blank=True, default=None, null=True)),
                ('ora_inizio', models.IntegerField(max_length=50)),
                ('ora_fine', models.IntegerField(max_length=50)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni', to='gestione.campo')),
                ('utente', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campi_prenotati', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
