# Generated by Django 4.0.4 on 2022-06-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0002_alter_campo_id_prenotazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='giocatori',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='campo',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='campo',
            name='mq',
            field=models.IntegerField(default=90),
        ),
    ]
