# Generated by Django 4.0.4 on 2022-06-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0003_campo_giocatori_alter_campo_id_alter_campo_mq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
