# Generated by Django 4.0.4 on 2022-06-09 19:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0004_alter_campo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giorno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno', models.PositiveSmallIntegerField(choices=[(1, 'Lunedi'), (2, 'Martedi'), (3, 'Mercoledi'), (4, 'Giovedi'), (5, 'Venerdi'), (6, 'Sabato'), (7, 'Domenica')])),
            ],
        ),
        migrations.CreateModel(
            name='Ora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ora', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.DeleteModel(
            name='Prenotazione',
        ),
        migrations.AddField(
            model_name='giorno',
            name='ore',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.ora'),
        ),
        migrations.AddField(
            model_name='campo',
            name='giorni',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.giorno'),
        ),
    ]
