# Generated by Django 4.0.4 on 2022-06-09 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestione', '0006_remove_campo_giorni_remove_giorno_ore_giorno_campo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='utente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campi_posseduti', to=settings.AUTH_USER_MODEL),
        ),
    ]
