# Generated by Django 4.0.4 on 2022-06-10 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0010_alter_campo_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ora',
            old_name='giorni',
            new_name='giorno',
        ),
    ]
