# Generated by Django 4.0.4 on 2022-06-13 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0013_alter_giorno_giorno'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='giorno',
            unique_together={('giorno', 'campo')},
        ),
    ]
