# Generated by Django 4.0.5 on 2022-06-16 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0014_alter_giorno_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ora',
            unique_together={('giorno', 'ora')},
        ),
    ]
