# Generated by Django 4.0.5 on 2022-06-18 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0017_alter_giorno_giorno'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prenotazione',
            unique_together={('data', 'ora')},
        ),
    ]
