# Generated by Django 4.0.5 on 2022-06-21 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestione', '0018_alter_prenotazione_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='utente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utente', to=settings.AUTH_USER_MODEL),
        ),
    ]
