# Generated by Django 4.0.5 on 2022-06-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0019_prenotazione_utente'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='cap',
            field=models.IntegerField(default=41212),
            preserve_default=False,
        ),
    ]
