# Generated by Django 4.0.5 on 2022-06-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0020_campo_cap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campo',
            options={'ordering': ['prezzo']},
        ),
        migrations.AddField(
            model_name='campo',
            name='tipo_erba',
            field=models.CharField(choices=[('Sintetico', 'Sintetico'), ('Erba Vera', 'Erba Vera'), ('Cementato Esterno', 'Cementato Esterno'), ('Cementato Interno', 'Cementato Interno')], default='Erba Vera', max_length=100),
            preserve_default=False,
        ),
    ]
