# Generated by Django 4.0.5 on 2022-06-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0021_alter_campo_options_campo_tipo_erba'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='immagine',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='campo'),
        ),
    ]
