# Generated by Django 4.0.5 on 2022-06-25 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0024_recensione_utente'),
    ]

    operations = [
        migrations.AddField(
            model_name='recensione',
            name='campo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campo_recensito', to='gestione.campo'),
        ),
    ]
