# Generated by Django 4.0.5 on 2022-06-25 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0026_alter_recensione_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recensione',
            name='stelle',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
