# Generated by Django 4.0.5 on 2022-06-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0027_alter_recensione_stelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='rates',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
