# Generated by Django 4.0.5 on 2022-06-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0029_remove_campo_rates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prenotazione',
            options={'ordering': ['-data']},
        ),
        migrations.AlterField(
            model_name='campo',
            name='immagine',
            field=models.ImageField(default='img/logo.jpg', upload_to='campo'),
        ),
    ]
